import setuptools

setuptools.setup(
    name="TractSeg",
    version="3.0",
    description="Fast and accurate segmentation of white matter bundles",
    long_description="See README.md for more details.",
    url="https://github.com/bertan-karacora/TractSeg/",
    python_requires=">=3.9",
    license="Apache 2.0",
    packages=setuptools.find_packages(),
    install_requires=[
        "dipy",
        "fury",
        "joblib",
        "matplotlib",
        "nibabel",
        "numpy",
        "psutil",
        "pyyaml",
        "requests",
        "scikit-learn",
        "scipy",
        "seaborn",
        "tqdm",
        "xvfbwrapper",
    ],
    zip_safe=False,
    classifiers=[
        "Intended Audience :: Science/Research",
        "Programming Language :: Python",
        "Topic :: Scientific/Engineering",
        "Operating System :: Unix",
        "Operating System :: MacOS",
    ],
    scripts=[
        "scripts/TractSeg",
        "scripts/ExpRunner",
        "scripts/Tractometry",
        "scripts/Tracking",
    ],
    include_package_data=True,
)
