import setuptools

setuptools.setup(
    name="TractSeg",
    version="2.9",
    description="Fast and accurate segmentation of white matter bundles",
    long_description="See README.md for more details.",
    url="https://github.com/bertan-karacora/TractSeg/",
    python_requires=">=3.8",
    license="Apache 2.0",
    packages=setuptools.find_packages(),
    install_requires=[
        "future",
        "numpy",
        "nibabel>=2.3.0",
        "matplotlib",
        "scikit-learn",
        "scipy",
        "tqdm",
        "six",
        "psutil",
        "dipy>=1.5.0",
        "fury",
        "joblib>=0.13.2",
        "seaborn",
        "requests",
        "xvfbwrapper",
        "pyyaml",
    ],
    zip_safe=False,
    classifiers=[
        "Intended Audience :: Science/Research",
        "Programming Language :: Python",
        "Topic :: Scientific/Engineering",
        "Operating System :: Unix",
        "Operating System :: MacOS",
    ],
    scripts=[
        "bin/TractSeg",
        "bin/ExpRunner",
        "bin/flip_peaks",
        "bin/calc_FA",
        "bin/Tractometry",
        "bin/download_all_pretrained_weights",
        "bin/Tracking",
        "bin/rotate_bvecs",
        "bin/plot_tractometry_results",
        "bin/get_image_spacing",
        "bin/remove_negative_values",
    ],
    include_package_data=True,
)
