TYPE_EXP: "tract_segmentation" # tract_segmentation|endings_segmentation|dm_regression|peak_regression

# Input data
DATASET: "HCP105"
PATH_DATA: "/data/HCP"
DIR_FEATURES: "peaks"
FILENAME_FEATURES: "peaks_cropped.nii.gz"
DIR_LABELS: "bundle_masks"
CLASSSET: "bundles_all72"
FILENAME_LABELS: "bundle_masks_cropped.nii.gz"

NR_OF_GRADIENTS: 9
RESOLUTION: "1.25mm" # 1.25mm|2.5mm
TYPE_LABELS: "int"
THRESHOLD: 0.5 # Binary: 0.5, Regression: 0.01

# Hyperparams
MODEL: "UNet_Pytorch_DeepSup"
SHAPE_INPUT: [144, 144]
BATCH_SIZE: 40
LEARNING_RATE: 0.001
LR_SCHEDULE: True
LR_SCHEDULE_MODE: "min" # min|max
LR_SCHEDULE_PATIENCE: 20
UNET_NR_FILT: 64
EPOCH_MULTIPLIER: 1 # 2D: 1, 3D: 12 for lowRes, 3 for highRes
NUM_EPOCHS: 250
TRAINING_SLICE_DIRECTION: "xyz" # y|xyz
LOSS_FUNCTION: "default" # default|soft_batch_dice
OPTIMIZER: "Adamax" # TODO: Or Adam?
LOSS_WEIGHT: null # null: no weighting
LOSS_WEIGHT_LEN: -1 # -1: constant over all epochs
BATCH_NORM: False
WEIGHT_DECAY: 0
USE_DROPOUT: True # slightly less overfitting (but max f1_validate maybe slightly worse (makes sense if less overfitting))
DROPOUT_SAMPLING: False
SAVE_WEIGHTS: True
RESET_LAST_LAYER: False
UPSAMPLE_TYPE: "bilinear" # bilinear|nearest
BEST_EPOCH_SELECTION: "f1" # f1|loss
METRIC_TYPES: ["loss", "f1_macro"]
FP16: True
PEAK_DICE_THR: [0.95]
PEAK_DICE_LEN_THR: 0.05
FLIP_OUTPUT_PEAKS: False # flip peaks along z axis to make them compatible with MITK
USE_VISLOGGER: False
NUM_SLICES: 1
PRINT_FREQ: 20
NORMALIZE_SLICES: True
NORMALIZE_PER_CHANNEL: False
CALC_F1: True
TEST_TIME_DAUG: False
PAD_TO_SQUARE: True

# Data augmentation
DATA_AUGMENTATION: True
DAUG_RESCALING: [0.9, 1.5]
DAUG_SCALE: True
DAUG_NOISE: True
DAUG_NOISE_VARIANCE: [0, 0.05]
DAUG_ELASTIC_DEFORM: True
DAUG_ALPHA: [90.0, 120.0]
DAUG_SIGMA: [9.0, 11.0]
DAUG_RESAMPLE: False # does not improve validation dice (if using Gaussian_blur) -> deactivate
DAUG_GAUSSIAN_BLUR: True
DAUG_BLUR_SIGMA: [0, 1]
DAUG_ROTATE: False
DAUG_ROTATE_ANGLE: [-0.78539816339, 0.78539816339] # rotation: 2*np.pi: 360 degree  (0.4 ~= 22 degree, 0.2 ~= 11 degree))
SPATIAL_TRANSFORM: "SpatialTransformPeaks" # SpatialTransform|SpatialTransformPeaks
P_SAMP: 1.0
